// Generated by components discovery
declare module 'vue' {
  export interface GlobalComponents {
    'DaisyuiThemeSwitcher': typeof import('../components/DaisyuiThemeSwitcher.vue')['default'],
    'ReloadPrompt': typeof import('../components/ReloadPrompt.vue')['default'],
    'CommonBreadcrumb': typeof import('../components/common/Breadcrumb.vue')['default'],
    'CommonFooter': typeof import('../components/common/Footer.vue')['default'],
    'CommonHeader': typeof import('../components/common/Header.vue')['default'],
    'CommonImageoverlay': typeof import('../components/common/Imageoverlay.vue')['default'],
    'CommonMobilebottommenu': typeof import('../components/common/Mobilebottommenu.vue')['default'],
    'IconHome': typeof import('../components/icon/home.vue')['default'],
    'LoadingArt': typeof import('../components/loading/Art.vue')['default'],
    'LoadingName': typeof import('../components/loading/Name.vue')['default'],
    'LoadingRestorephoto': typeof import('../components/loading/Restorephoto.vue')['default'],
    'LoadingText': typeof import('../components/loading/Text.vue')['default'],
    'LoadingSkeletonOnLoadCommentCard': typeof import('../components/loading/skeleton-on-load-comment-card.vue')['default'],
    'LoadingSkeletonOnLoadCommentsCard': typeof import('../components/loading/skeleton-on-load-comments-card.vue')['default'],
    'LoadingSkeletonOnLoadUserCard': typeof import('../components/loading/skeleton-on-load-user-card.vue')['default'],
    'CommonHeaderMegamenu': typeof import('../components/common/header/Megamenu.vue')['default'],
    'CommonHeaderSearch': typeof import('../components/common/header/Search.vue')['default'],
    'NuxtWelcome': typeof import('../node_modules/nuxt3/dist/app/components/nuxt-welcome.vue')['default'],
    'ClientOnly': typeof import('../node_modules/nuxt3/dist/app/components/client-only')['default']
  }
}
export {}
