// Generated by nitro
declare module '@nuxt/nitro' {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/': Awaited<ReturnType<typeof import('../server-middleware/sw').default>>
  }
}
export {}